<div class="content_header"><h2>ABOUT THE SITE</h2></div>
<div class="about_info">
<h4>What's the site's theme? Who's the audience?</h4>
<p>If it is not clear, the site is based upon ULTRAKILL's representations of the Nine Layers of Hell, which itself is an interpretation of Biblical Hell by Dante Aligheri in the Divine Comedy.<br />While the site's theme leans more into "gaming", I simply wanted a theme that could not only represent "me" but also fulfill the tasks both required in the subject and things I want to execute from other students.<br />Ultimately, the audience is myself, you (likely also a student interested in gaming), and Prof.</p>
<h4>What are each of the layers for?</h4>
<p>The layout of the site is split into three sections, respective of the three acts ULTRAKILL divides hell into: Act 1 being the introduction of myself, the general purpose of the website back in midterms, Act 2 being a place for all the "queries" which require MySQL, and Act 3 supposedly being for "fun stuff" that goes beyond what I've first heard of the subject. Fortunately, not only has there not been anything after PHP, but also that we know nothing on Fraud as it is in development at the time of making this site.<br />Each layer's individual purpose is already laid out in bold text upon first descent, so I shan't elaborate. </p>
<h4>What happened to Lust?</h4>
<p>Lust is the page that's been last "completed" of all pages, closest to the final voting deadline. To make it fit, I cut a lot of corners and sized it down significantly in every aspect as to not to waste too much of my time trying to find ways to make it work. In the end, it should work out.<br />Still, it's unfortunate that Lust is practically a lie because it can't have everything I wanted in.</p>
<h4>What's with all the form-based pages?</h4>
<p>Firstly, we had two tasks that related to databases: The first being a feedback/guest form (which is Wrath), and the second being a news form (which is Greed). I planned on Greed being multi-page, but I was surprised at how this turned out. Wrath was made first, for the PHP part of the course. Later on, with CodeIgniter, we were made to do its News tutorial, which sits in Greed now. Hell, even CodeIgniter's given examples remain on the database for Greed.<br>As for Heresy, I always wanted to duplicate what that one former winning site did with image sharing, because it felt like a treat to have fellow classmates submit any (safe-for-work) images up for display on my site.</p>
<h4>Was Violence always an ULTRAKILL advertisement?</h4>
<p>Yes. The reason it's not up to what I wanted is because the sole video I wanted on the page does not exist, nor did I have the time to make it exist.</p>
</div>